### ISSUE TITLE
BT-21 Subject code implemented incorrect

### ISSUE THREAD

**Issue by AndreasPvd** [itplr-kosit/xrechnung-testsuite#2]
Hello,

it looks like the Note Subject code was implemented incorrect in the UBL instance files.
The mapping TS says that the code should be surrounded by `#` 

In your instances you do it as follows:

`<cbc:Note>ADU</cbc:Note>`
`<cbc:Note>here comes the textual note</cbc:Note>`

according to the tests in
https://github.com/CenPC434/validation/blob/master/ubl/schematron/UBL/EN16931-UBL-model.sch and the closed question on https://github.com/CenPC434/validation/issues/41 it should look like

`<cbc:Note>#ADU#here comes the textual note</cbc:Note>`

BR,
Andreas

**Comment by rkottmann** [comment]
corrected., already quiet some time ago. thx
