### ISSUE TITLE
BR-E-10 Issue in 02.01a-INVOICE_uncefact.xml

### ISSUE THREAD

**Issue by phax** [itplr-kosit/xrechnung-testsuite#3]
This file is missing the
```xml
                <ram:ExemptionReasonCode>...</ram:ExemptionReasonCode>
```
for the `ram:ApplicableTradeTax` with the `<ram:CategoryCode>` value of `E`

**Comment by rkottmann** [comment]
thx for reporting. All what is wrong in testsuite hints towards errors in the schematron rules.

In this case it seems that CEN CII rule never fires:

```xml
 <xsl:template match="//rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:ApplicableTradeTax/ram:CategoryCode[. = 'E'][upper-case(ram:TypeCode) = 'VAT']"
```
It should most probably be:
```xml
 <xsl:template match="//rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:ApplicableTradeTax[ ram:CategoryCode = 'E'][upper-case(ram:TypeCode) = 'VAT']"
```

However, we are testing it currently and will then report it.

**Comment by rkottmann** [comment]
I am closing cause we slowly but surely move away from GitHub.

Therefore, I am disabling the issue feature of this project.

Further development is in https://projekte.kosit.org/xrechnung/xrechnung-testsuite/-/issues/36
