### ISSUE TITLE
Wrong `schemeID` in 02.01a-INVOICE_uncefact.xml and 02.02a-INVOICE_uncefact.xml

### ISSUE THREAD

**Issue by phax** [itplr-kosit/xrechnung-testsuite#4]
Same errors in both files:
* ram:SellerTradeParty/ram:ID/@schemeID = "MC:VAT"
* ram:SellerTradeParty/ram:SpecifiedLegalOrganizationram:ID/@schemeID = "MC:VAT"
* ram:BuyerTradeParty/ram:SpecifiedLegalOrganizationram:ID/@schemeID = "DE:LID"

Please use an ISO6523 code like "0088" or "0204"

**Comment by rkottmann** [comment]
Also here thx for spotting.

Again most prob also an issue of CEN Schematron. However, we fixed test instances already with this commit https://github.com/itplr-kosit/xrechnung-testsuite/commit/01f0a125efc0256ce637735c1487cd311f83d22d
