### ISSUE TITLE
[BR-53] in multiple un/cefact files, e.g. 01.11a-INVOICE_uncefact.xml

### ISSUE THREAD

**Issue by jstaerk** [itplr-kosit/xrechnung-testsuite#5]
The 1.3.1 release of https://github.com/ConnectingEurope/eInvoicing-EN16931/releases seems to report e.g. on 01.11a-INVOICE_uncefact.xml  in location "/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:SupplyChainTradeTransaction[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:ApplicableHeaderTradeSettlement[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]/*:SpecifiedTradeSettlementHeaderMonetarySummation[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]" 

a violation of the test 
"not(/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:TaxCurrencyCode) or (/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:TaxCurrencyCode and (ram:TaxTotalAmount/@currencyID = /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:TaxCurrencyCode) and not(/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:TaxCurrencyCode = /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode))"

i.e. a [BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.

I'm a bit puzzled because both taxcurrencycode and invoicecurrencycode seem to be present and match the ram:TaxTotalAmount @currencyID attribute?

**Comment by bahaabeih** [comment]
Same problem here, with EN16931 releases 1.3.1 and 1.3.2

**Comment by rkottmann** [comment]
Thx for spotting and reporting 😄 

This was fixed with https://github.com/itplr-kosit/xrechnung-testsuite/commit/2e7b961f648435047615b0ccd41c3249b7bf6e63

Will be included in next release.
